### ISSUE TITLE
Shard config merge

### ISSUE THREAD

**Issue by joshystuart** [zoopcommerce/shard-module#12]
`shard` extension configs are being dropped somewhere along the way in `shrad-module`

For example, in the `Zoop\Shard\Serializer\Extension` there's invokables such as `'serializer.type.collection'` which is missing once all the configs are merged. This causes a `ServiceManager` failure when trying to retrieve these classes. This doesn't happen when running `shard` on it's own.

I'm not sure if it's taking place in here:
https://github.com/zoopcommerce/shard-module/blob/master/src/Zoop/ShardModule/ConfigMergeListener.php#L62

Or if it's a systemic issue from here: https://github.com/zoopcommerce/shard/blob/master/lib/Zoop/Shard/Manifest.php#L173 (ie. why are we using `array_intersect_key`?)

I'm not real familiar which `shrad-module` so I'm hoping you may be able to help me out. Particularly because there's so much going on with the config at the `shard-module` stage.

**Comment by superdweebie** [comment]
Yep, `shard-module` config is messy. zf2 merges all the module configs, then shard-module takes that merged config and further modifies it so that shard-module and doctrine-module work together (I didn't want to rewrite doctrine-module, so messy config modification is the way to work with it.)

I'll look into it.

**Comment by joshystuart** [comment]
Thanks! I'll take a look again tomorrow with fresh eyes. Been a long day :)

**Comment by joshystuart** [comment]
I tried to make sense of this today but no luck. If you are able to look into this tomorrow that would be AMAZING!

**Comment by superdweebie** [comment]
I'll give it a go.

**Comment by superdweebie** [comment]
I've just added a new test for this in `shard-module` (I'll push later tonight). And it's passing without any changes. Are you using the correct service manager? It's set up like this:
- Shared zf2 service manager - has things like zf2 moduleManager, router, etc.
- Each shard manifest has its own service manager, separate from the shared zf2 service manager. You can get the specific shard service manager through the shared service manager like this: `$shardSm = $sharedSm->get('shard.default.servicemanager')`.
- Using the `$shardSm` then you can get normal shard services like `$serializer = $shardSm->get('serializer')`
- You can also pull shard services direct from the shared zf2 service manager if you add a `shard.<manifest>` prefix. Eg `$serializer = $sharedSm->('shard.default.serializer')`.

Under the hood the action is happening in this class: https://github.com/zoopcommerce/shard-module/blob/master/src/Zoop/ShardModule/Service/ShardServiceAbstractFactory.php. That abstract factory looks for requests for services with names following the pattern `'/^shard\.(?<manifestName>[a-z0-9_]+)\.(?<serviceName>[a-z0-9_.]+)$/'`.

Does that help, or have I missed something?

**Comment by joshystuart** [comment]
I'll create a test that recreates the error I'm seeing because it's a little confusing to try and articulate in words.

It should be noted however, it's not me, but shard that is looking for services that are missing. 

I'll get back to you shortly.

**Comment by superdweebie** [comment]
Ok

**Comment by joshystuart** [comment]
@superdweebie I'm still getting some issues with config, primarily around extensions in the `ServiceManager` eg. `'serializer.reference.lazy'`. I'm trying to get to the bottom of it but wanted to ask a few questions;
- Why doesn't the `POST`/`create` function return the new document in the `content` response? How else do we get the `id` of the newly created document?
- Should we create referenced objects in a POST? Or should we create them all, then pass as reference?

**Comment by joshystuart** [comment]
Oh, I see I could use `$response->getHeaders()->get('Location')->toString()` to get the `ID`, but it does require some string manipulation.

Thoughts?

**Comment by superdweebie** [comment]
From a rest perspective, it didn't seem right to return the document in a POST create response, because it is just double handling - you're sending back what was sent to the server. From my reading of the HTTP specs, the Location header was the right one to populate. We could add something like an `x-id` header if you think it is needed.

Regarding references, you should be able to send a json document with all references populated and shard should handle it correctly - creating both the parent document and all the referenced documents all in the one go.

**Comment by joshystuart** [comment]
Fair enough. I think something in the header would be beneficial.

For me the child reference documents aren't created automatically. I'll add tests so you can reproduce.

Also this is the problem I'm seeing in `Commerce`:

```
Exception: Zend\ServiceManager\ServiceManager::get was unable to fetch or create an instance for serializer.reference.lazy
```

**Comment by joshystuart** [comment]
I'm guessing that error indicates that the wrong `ServiceLocator`/`ServiceManager` is being used?

By the way, the error is occurring here: https://github.com/zoopcommerce/shard/blob/master/lib/Zoop/Shard/Serializer/Serializer.php#L270

**Comment by superdweebie** [comment]
I think I know what's going wrong with the ServiceManager. I'm guessing you're pulling the serializer with `serviceManager->get('shard.commerce.serializer')`? The application serviceManager (not the shard manifest service manager) is seeing the `ServiceLocatorAwareInterface` on the serializer and injecting itself over the top of the shard manifest service manager. A small amount of refacoring to remove `ServiceLocatorAwareInterface` from the serializer will fix it.

**Comment by joshystuart** [comment]
Found the problem;

I was using the following to get the `Serializer`:

``` php
$serializer = $serviceLocator->get('shard.commerce.serializer');
```

Which caused the aforementioned error because the main/zf2 `ServiceManager` was added to the class.

However, if I get the `Serializer` in the following way:

``` php
$manifest = $serviceLocator->get('shard.commerce.manifest');
/* @var $manifest \Zoop\Shard\Manifest */
$serializer = $manifest->getServiceManager()->get('serializer');
```

It works because it uses the correct `Shard` `ServiceManager`.

I don't know exactly why, but you will probably know straight away.

**Comment by superdweebie** [comment]
Snap!

**Comment by superdweebie** [comment]
Just doing a quick search, there are 25 uses of `ServiceLocatorAwareInterface` in shard. Every one of those is going to have this exact same problem. I'll work on a fix.

**Comment by joshystuart** [comment]
@superdweebie great minds!

Glad we got to the bottom of that one. Been doing my head in! hahaha

**Comment by joshystuart** [comment]
For now I've replaced all references getting the `Serializer`, to use the `Manifest` instead.

**Comment by superdweebie** [comment]
I'd forgotten about this one. Rather than grabbing the manifest, you can do it in one line like this:

```
$serializer =  $serviceLocator->get('shard.commerce.servicemanager')->get('serializer');
```

**Comment by joshystuart** [comment]
Thanks, yeah. That's how I've been doing it. :D
