### ISSUE TITLE
Duplicate events in listener configs

### ISSUE THREAD

**Issue by joshystuart** [zoopcommerce/shard-module#20]
@superdweebie I'm finding that occasionally I get a `rest` config that duplicates the listeners (see below):

![double-triggering](https://cloud.githubusercontent.com/assets/3791360/3787250/0ecb0b38-1a0b-11e4-8910-297d2cef4255.png)

Any thoughts on what could be causing that?

I've pushed my WIP `user-module` to see if you can see any bad code on my part.

[Check this test](https://github.com/zoopcommerce/commerce-user-module/blob/master/tests/Zoop/User/Test/Controller/ZoopAdminTest.php)

If you check out the listeners I've only [defined them once](https://github.com/zoopcommerce/commerce-user-module/blob/master/config/module.config.php#L78) but they show up twice.

I could dig into where these listener configs are merged, but any chance you could point me in the right direction?

**Comment by superdweebie** [comment]
Hmm. Definitely not good. I don't know what is happening, but I'd start by putting a breakpoint here: https://github.com/zoopcommerce/shard-module/blob/master/src/Zoop/ShardModule/Controller/RestfulController.php#L50

**Comment by joshystuart** [comment]
Will do. Thanks

**Comment by joshystuart** [comment]
I think maybe I've defined an endpoint for `users` somewhere else because it comes from `config` as is. Hm. We don't define it in `gateway` or `gomi` do we?

**Comment by joshystuart** [comment]
Found it! My fault!

I was including the config twice, one when the module was included and once explicitly: https://github.com/zoopcommerce/commerce-user-module/blob/master/tests/test.application.config.php#L18

Sorry for the trouble.

**Comment by superdweebie** [comment]
no problem at all. glad it was found quickly.
