### ISSUE TITLE
Filtering on Collection

### ISSUE THREAD

**Issue by joshystuart** [zoopcommerce/shard-module#3]
Hey @superdweebie 

I couldn't get the current `master` of shard working (not sure if there are different configs etc), so I couldn't fix the filtering issues. However, the following code works in `v1.2` if you want to add it (will add unit tests when I can).

https://github.com/zoopcommerce/shard-module/blob/master/src/Zoop/ShardModule/Controller/JsonRestfulController/GetListAssistant.php#L172

``` php
protected function addCriteriaToQuery($query, $criteria)
    {
        $metadata = $this->metadata;
        foreach ($criteria as $field => $value) {
            $mappingType = $metadata->getFieldMapping($field)['type'];
            if (is_array($value) || $mappingType == 'collection') {
                $value = is_array($value) ? $value : [$value];
                $query->field($field)->in($value);
            } elseif ($mappingType == 'int') {
                $query->field($field)->equals((integer) $value);
            } else {
                $query->field($field)->equals($value);
            }
        }

        return $query;
    }
```

**Comment by superdweebie** [comment]
Great. I'll add it to master before we tag again.
