### ISSUE TITLE
Referenced documents

### ISSUE THREAD

**Issue by joshystuart** [zoopcommerce/shard-module#4]
Hey @superdweebie 

How are we going to handle referenced documents with the api? 

Currently they aren't fetched which is a problem for cases such as: https://github.com/zoopcommerce/ZoopCommerce/blob/release/api/module/Api/src/Zoop/Api/DataModel/Address.php#L51 where the `Country` is a reference and contains currency info etc.

**Comment by superdweebie** [comment]
Hey,

Use an eager serializer, and they will be fetched. Eg:

```
/**
 * @ODM\ReferenceOne(targetDocument="FlavourEager")
 * @Shard\Serializer\Eager
 */
protected $flavour;
```

**Comment by joshystuart** [comment]
<3 !

**Comment by joshystuart** [comment]
That meant "thanks" by the way

**Comment by superdweebie** [comment]
I should mention, shard has three reference serializers built in: Eager, RefLazy and SimpleLazy, and you can also write your own.
