### ISSUE TITLE
Filtering on subdocuments

### ISSUE THREAD

**Issue by joshystuart** [zoopcommerce/shard-module#5]
@superdweebie sorry to bug you with all these questions, but does shard currently allow you to filter on sub-documents? eg. `'brand.name': 'The Amity Affliction'`

**Comment by superdweebie** [comment]
Yes, but it's in master, not the current tagged version, so you'll have it real soon.

**Comment by superdweebie** [comment]
Nice band name

**Comment by joshystuart** [comment]
Great. Thanks!

Yeah, they aren't bad ;)

**Comment by superdweebie** [comment]
It's in shard 2.0
